name: pause
on:
  workflow_dispatch: 
  schedule:
    - cron:  0 19 * * * 
env: 
    PHONE: ${{ secrets.PHONE }}
    PASSWORD: ${{ secrets.PASSWORD }}
    TOKEN: ${{ secrets.TOKEN }}
jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3        
      - name: Set up env
        run: pip install requests
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
      - name: Checkin
        run: |
          python main.py 
  

